### ISSUE TITLE
List of remaining AnythingMC software [Updated]

### ISSUE THREAD

**Issue by TonimatasDEV** [UeberallGebannt/server-softwares#53]
I have a document with the remaining AnythingMC software. If you add any of these softwares you can delete it in the document commenting it, when I confirm it I will delete it definitively.

[Document](https://docs.google.com/document/d/1ehLl6Ae66QClDEHuM1YHP8ciNqvTR-0P6A2gPErmajk/edit?usp=sharing)

Close #24

**Comment by UeberallGebannt** [comment]
Please don't open a new issue for an already existing one, update/add to the old one instead :)
