### ISSUE TITLE
MCPC+, spigot, bukkit and paper

### ISSUE THREAD

**Issue by JustDoom** [UeberallGebannt/server-softwares#9]
MCPC+ had versions for 1.2.5 and 1.6.2 as well

also just remembered. for spigot it started at 1.3.2 (maybe earlier but cant find any files) and bukkit the earliest i know of was 1.2 beta

and paper was in 1.13.2

**Comment by UeberallGebannt** [comment]
Fixed Spigot, Bukkit and Paper

Couldnt find MCPC+ versions, do you have any source for that?

**Comment by SparkGNRK** [comment]
I know that there is MCPC+ at least for 1.4.7, 1.5.1/1.5.2 and 1.6.2 but all download website seems to be down

1.4.7 : http://ci.md-5.net/job/MCPC-Legacy-147/

1.5.1/1.5.2 : http://ci.md-5.net/job/MCPC-Plus-Legacy/

1.6.2 : http://ci.md-5.net/job/MCPC-Plus/

**Comment by JustDoom** [comment]
> Fixed Spigot, Bukkit and Paper
> 
> Couldnt find MCPC+ versions, do you have any source for that?

https://www.mediafire.com/file/ghurs6v5txl7w66/MCPC%252B.zip/file
1.2.5, 1.6.2, 1.6.4, 1.7.2 and 1.7.10 are in there

**Comment by JustDoom** [comment]
Also purpur started in 1.14.1 not 1.14.4

**Comment by UeberallGebannt** [comment]
Fixed in [c97f5e2](https://github.com/UeberallGebannt/server-softwares/commit/c97f5e2680f58602cdef8e127495178b4dc0240b)
